# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  # A short description of the repository that will show up on GitHub
  description: A template for new repositories

  # A URL with more information about the repository
  homepage: https://github.com/Bradford1040/repo_template_adds

  # A comma-separated list of topics to set on the repository
  topics: template, github

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Either `true` to enable issues for this repository, `false` to disable them.
  has_issues: true

  # Either `true` to enable projects for this repository, or `false` to disable them.
  has_projects: true

  # Either `true` to enable the wiki for this repository, or `false` to disable it.
  has_wiki: true

  # Either `true` to enable downloads for this repository, or `false` to disable them.
  has_downloads: true

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

  # Either `true` to automatically delete head branches when pull requests are
  # merged, or `false` to prevent automatic deletion.
  delete_branch_on_merge: true

  # Either `true` to enable automatic vulnerability alerts, or `false` to disable them.
  enable_vulnerability_alerts: true

  # Either `true` to enable automated security fixes, or `false` to disable them.
  enable_automated_security_fixes: true

  # Either `true` to enable strict commit signing, or `false` to disable it.
  enable_strict_commit_signing: true
