blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/Bradford1040/repo_template_adds/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Vulnerability
    url: https://github.com/Bradford1040/repo_template_adds/security/policy
    about: Please report security vulnerabilities here.
